# Generated by Django 5.0.4 on 2026-09-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number / WhatsApp')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('verification', 'Technician Verification & Badges'), ('hiring', 'Employer & Hiring Support'), ('billing', 'Billing, Payments & Escrow'), ('dispute', 'Dispute or Safety Concern'), ('partnership', 'Business Partnership & Press'), ('technical', 'Technical Issue / Bug Report')], default='general', max_length=30, verbose_name='Inquiry Topic')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New (Unread)'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for support agents handling this inquiry')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Registered user who submitted this inquiry (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
