# Generated by Django 5.0.4 on 2026-06-23 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ver_type', models.CharField(choices=[('nin', 'NIN'), ('bvn', 'BVN'), ('cac', 'CAC')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'API Error')], default='pending', max_length=10)),
                ('identifier_hint', models.CharField(blank=True, help_text='Last 4 chars of the submitted ID, for audit display only.', max_length=40)),
                ('dojah_ref', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Attempt',
                'verbose_name_plural': 'Verification Attempts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VerificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Identity Verified (NIN)'), (2, 'Enhanced Verified (BVN)'), (3, 'Business Verified (CAC)')], db_index=True, default=0)),
                ('nin_verified', models.BooleanField(default=False)),
                ('nin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('nin_last4', models.CharField(blank=True, max_length=4)),
                ('nin_dojah_ref', models.CharField(blank=True, help_text='Dojah transaction reference', max_length=120)),
                ('bvn_verified', models.BooleanField(default=False)),
                ('bvn_verified_at', models.DateTimeField(blank=True, null=True)),
                ('bvn_last4', models.CharField(blank=True, max_length=4)),
                ('bvn_dojah_ref', models.CharField(blank=True, max_length=120)),
                ('cac_verified', models.BooleanField(default=False)),
                ('cac_verified_at', models.DateTimeField(blank=True, null=True)),
                ('cac_rc_number', models.CharField(blank=True, max_length=30)),
                ('cac_company_name', models.CharField(blank=True, max_length=200)),
                ('cac_dojah_ref', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Profile',
                'verbose_name_plural': 'Verification Profiles',
            },
        ),
    ]
