# Generated by Django 5.0.4 on 2026-04-03 22:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TradeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("icon_class", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "clip_context_text",
                    models.TextField(
                        blank=True,
                        help_text="Short natural-language description used to anchor CLIP embeddings for this trade (e.g. 'expert electrician wiring installation Lagos').",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trade Category",
                "verbose_name_plural": "Trade Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=256)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual / Homeowner"),
                            ("sme", "Small / Medium Business"),
                            ("corporation", "Large Corporation"),
                            ("ngo", "NGO / Non-Profit"),
                            ("government", "Government Agency"),
                        ],
                        default="sme",
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("about", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employer_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("fct", "FCT — Abuja"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                        ],
                        max_length=40,
                    ),
                ),
                ("lga", models.CharField(blank=True, max_length=120)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Admin-confirmed verified employer. Shown with a badge.",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_verified", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "description",
                    models.TextField(
                        help_text="Full job description. This is the primary text encoded by CLIP for matching workers to this job."
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("once_off", "One-Off / Gig"),
                            ("internship", "Apprenticeship / Internship"),
                        ],
                        default="once_off",
                        max_length=20,
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Per Hour"),
                            ("daily", "Per Day"),
                            ("weekly", "Per Week"),
                            ("monthly", "Per Month"),
                            ("fixed", "Fixed Price"),
                            ("negotiable", "Negotiable"),
                        ],
                        default="negotiable",
                        max_length=20,
                    ),
                ),
                (
                    "pay_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum pay in NGN",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pay_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum pay in NGN",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("fct", "FCT — Abuja"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                        ],
                        max_length=40,
                    ),
                ),
                ("lga", models.CharField(blank=True, max_length=120)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "slots",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="How many workers are needed for this job."
                    ),
                ),
                (
                    "clip_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="CLIP text embedding of this job. 512-dim float list. Recomputed when the job is saved.",
                        null=True,
                    ),
                ),
                ("clip_embedding_updated", models.DateTimeField(blank=True, null=True)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.employerprofile",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs", to="jobs.skill"
                    ),
                ),
                (
                    "trade_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.tradecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="jobs.tradecategory",
            ),
        ),
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry (0–2 years)"),
                            ("mid", "Intermediate (3–5 years)"),
                            ("experienced", "Experienced (6–10 years)"),
                            ("expert", "Expert (10+ years)"),
                        ],
                        default="entry",
                        max_length=20,
                    ),
                ),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Natural-language description of the worker's skills and experience. This is the primary text encoded by CLIP for job matching.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("fct", "FCT — Abuja"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Local Government Area"
                    ),
                ),
                ("is_willing_to_relocate", models.BooleanField(default=False)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate in NGN",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Day rate in NGN",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available Now"),
                            ("soon", "Available Soon"),
                            ("busy", "Currently Busy"),
                            ("unavailable", "Not Available"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set by admin after document/ID verification.",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured workers appear at the top of recommendation lists.",
                    ),
                ),
                (
                    "profile_completion",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percentage (0–100) calculated from filled profile fields.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "clip_text_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="CLIP text embedding of the worker's bio + skills. 512-dim float list. Recomputed on profile save.",
                        null=True,
                    ),
                ),
                ("clip_embedding_updated", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "trade_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="jobs.tradecategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-profile_completion", "-created"],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=280)),
                (
                    "clip_image_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="CLIP image embedding of this portfolio photo.",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "trade_context",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which trade this item demonstrates.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.tradecategory",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["worker", "display_order", "-created"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cover_note",
                    models.TextField(
                        blank=True,
                        help_text="Brief message from the worker to the employer.",
                    ),
                ),
                (
                    "clip_match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Snapshot of the CLIP similarity score when the application was made.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn by Worker"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employer_note", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="CLIPMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="CLIP cosine similarity score between worker embedding and job embedding.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_matches",
                        to="jobs.job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip_matches",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="WorkerSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("competent", "Competent"),
                            ("proficient", "Proficient"),
                            ("expert", "Expert"),
                        ],
                        default="competent",
                        max_length=20,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.skill"
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.workerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="workers",
                through="jobs.WorkerSkill",
                to="jobs.skill",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("new_match", "New Job Match"),
                            ("application_update", "Application Status Update"),
                            ("new_application", "New Application Received"),
                            ("new_review", "New Review"),
                            ("job_expiring", "Job Expiring Soon"),
                            ("profile_tip", "Profile Improvement Tip"),
                            ("system", "System Message"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="jobs_notifi_user_id_d5a9c6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("employer_to_worker", "Employer → Worker"),
                            ("worker_to_employer", "Worker → Employer"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Admin can hide inappropriate reviews."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="jobs.job",
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("job", "reviewer", "review_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "trade_category"], name="jobs_job_status_23fe98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["state", "status"], name="jobs_job_state_a78adf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("worker", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "worker")},
        ),
        migrations.AddIndex(
            model_name="clipmatch",
            index=models.Index(
                fields=["job", "-score"], name="jobs_clipma_job_id_f0c0ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clipmatch",
            index=models.Index(
                fields=["worker", "-score"], name="jobs_clipma_worker__f9c5fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clipmatch",
            unique_together={("worker", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="workerskill",
            unique_together={("worker", "skill")},
        ),
    ]
