# Generated by Django 5.0.4 on 2026-04-04 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_hybrid_scoring_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipmatch",
            name="experience_score",
            field=models.FloatField(
                blank=True,
                help_text="How well the worker experience level fits the job type (0–1).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clipmatch",
            name="location_score",
            field=models.FloatField(
                blank=True,
                help_text="1.0=same state, 0.5=willing to relocate/remote, 0.0=different state.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clipmatch",
            name="rating_score",
            field=models.FloatField(
                blank=True,
                help_text="Normalised average worker rating: (avg-1)/4. Default 0.5 if no ratings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clipmatch",
            name="score",
            field=models.FloatField(
                help_text="Weighted hybrid score: 50% text + 15% location + 15% experience + 10% image + 5% rating + 5% verification.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="clip_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Legacy CLIP text embedding. Use text_embedding instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="text_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Sentence-transformer embedding of title + trade + skills + description. 768-dim float list. Recomputed when job text changes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="clip_text_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Legacy CLIP text embedding. Use text_embedding instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="text_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Sentence-transformer embedding of bio + trade + skills. 768-dim float list. Recomputed when profile text changes.",
                null=True,
            ),
        ),
    ]
