# Generated by Django 5.0.4 on 2026-05-29 09:56

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_clipmatch_experience_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employerprofile",
            old_name="about",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="employerprofile",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="employerprofile",
            name="logo",
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: paste a YouTube link of you doing this work (e.g. https://www.youtube.com/watch?v=… or https://youtu.be/…). The video will be embedded on your public profile.",
                validators=[jobs.models.validate_youtube_url],
                verbose_name="YouTube Demo URL",
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual / Homeowner"),
                    ("sme", "Small / Medium Business"),
                    ("corporate", "Corporate / Large Business"),
                    ("ngo", "NGO / Non-profit"),
                    ("government", "Government / Public Sector"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
    ]
