# Generated by Django 5.0.4 on 2026-06-08 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_about_employerprofile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_match', 'New Job Match'), ('application_update', 'Application Status Update'), ('new_application', 'New Application Received'), ('new_review', 'New Review'), ('job_expiring', 'Job Expiring Soon'), ('profile_tip', 'Profile Improvement Tip'), ('system', 'System Message'), ('escrow_funded', 'Escrow Funded'), ('escrow_submitted', 'Work Submitted for Review'), ('escrow_approved', 'Milestone Approved'), ('escrow_released', 'Payment Released'), ('escrow_dispute', 'Dispute Raised')], max_length=30),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Auto-populated from the job title on save.', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage deducted from worker payout (e.g. 10.00 = 10%).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.jobapplication')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='jobs.employerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='jobs.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount the employer pays into escrow (NGN).', max_digits=12)),
                ('status', models.CharField(choices=[('unfunded', 'Unfunded'), ('funded', 'Funded (In Escrow)'), ('in_review', 'In Review'), ('approved', 'Approved'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='unfunded', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, help_text='Set to funded_at + 7 days when worker submits work.', null=True)),
                ('submission_note', models.TextField(blank=True, help_text="Worker's delivery note when submitting work.")),
                ('paystack_payment_ref', models.CharField(blank=True, help_text='Paystack transaction reference for the escrow charge.', max_length=100, null=True, unique=True)),
                ('paystack_transfer_ref', models.CharField(blank=True, help_text='Paystack transfer reference for the worker payout.', max_length=100, null=True)),
                ('worker_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after platform fee deduction, computed on release.', max_digits=12, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='jobs.contract')),
            ],
            options={
                'ordering': ['contract', 'display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('released_to_worker', 'Released to Worker'), ('refunded_to_employer', 'Refunded to Employer'), ('split', 'Split')], default='pending', max_length=30)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='jobs.milestone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(help_text='10-digit NUBAN account number.', max_length=10)),
                ('bank_code', models.CharField(help_text='Paystack bank code (e.g. "044" for Access Bank).', max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Created via Paystack Transfer Recipient API.', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Bank Account',
                'verbose_name_plural': 'Worker Bank Accounts',
            },
        ),
    ]
