# Generated by Django 5.0.4 on 2026-07-28 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_notification_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='jobs_notifi_user_id_d5a9c6_idx',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['worker', 'status'], name='jobs_jobapp_worker__3d76bb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'is_deleted'], name='jobs_notifi_user_id_0e0d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_deleted', '-created_at'], name='jobs_notifi_user_id_950b33_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'is_visible', 'review_type'], name='jobs_review_reviewe_5ce32a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['job'], name='jobs_review_job_id_be886c_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['trade_category', 'availability'], name='jobs_worker_trade_c_3a431f_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['state'], name='jobs_worker_state_4003c9_idx'),
        ),
    ]
