# Generated by Django 5.0.4 on 2026-08-18 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, help_text='Set to created_at + 7 days. Funds auto-release to worker if admin has not acted.', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Set True when dispute has been open 72h+ without resolution.'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='evidence_sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of the evidence file at upload time (tamper detection).', max_length=64),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediation_deadline',
            field=models.DateTimeField(blank=True, help_text='Set to created_at + 5 days. Admin cannot act until this passes.', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediation_employer_agreed',
            field=models.CharField(blank=True, help_text='Resolution the employer agreed to during mediation window.', max_length=30),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediation_worker_agreed',
            field=models.CharField(blank=True, help_text='Resolution the worker agreed to during mediation window.', max_length=30),
        ),
        migrations.AddField(
            model_name='dispute',
            name='split_worker_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For SPLIT resolution: percentage (0-100) released to the worker.', null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='dispute_flagged',
            field=models.BooleanField(default=False, help_text='Automatically set when dispute loss rate exceeds 40% with ≥3 disputes.'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='disputes_lost',
            field=models.PositiveIntegerField(default=0, help_text='Disputes resolved against this employer.'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='disputes_raised',
            field=models.PositiveIntegerField(default=0, help_text='Total disputes this employer has ever raised.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='dispute_flagged',
            field=models.BooleanField(default=False, help_text='Automatically set when dispute loss rate exceeds 40% with ≥3 disputes.'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='disputes_lost',
            field=models.PositiveIntegerField(default=0, help_text='Disputes resolved against this worker (as raiser or respondent).'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='disputes_raised',
            field=models.PositiveIntegerField(default=0, help_text='Total disputes this worker has ever raised.'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('unfunded', 'Unfunded'), ('funded', 'Funded (In Escrow)'), ('in_review', 'In Review'), ('approved', 'Approved'), ('pending_otp', 'Pending OTP (Transfer Awaiting Confirmation)'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='unfunded', max_length=20),
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='Message body — visible to both parties and admin.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='disputes/messages/')),
                ('attachment_sha256', models.CharField(blank=True, help_text='SHA-256 of attachment at upload time.', max_length=64)),
                ('is_admin_note', models.BooleanField(default=False, help_text='If True, only admin/staff can see this message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
