# Generated by Django 5.0.4 on 2026-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_dispute_auto_release_at_dispute_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1_10', '1–10 employees'), ('11_50', '11–50 employees'), ('51_200', '51–200 employees'), ('201_500', '201–500 employees'), ('500plus', '500+ employees')], help_text='Approximate number of full-time employees.', max_length=30),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry_sector',
            field=models.CharField(blank=True, help_text='e.g. Construction, Real Estate, Oil & Gas, Manufacturing.', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='year_founded',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the company was established.', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='employment_preference',
            field=models.CharField(choices=[('full_time', 'Full-Time Employment'), ('part_time', 'Part-Time Employment'), ('either', 'Either Full or Part-Time'), ('gig_only', 'Gig / Contract Work Only')], default='gig_only', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='expected_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly salary in NGN for full-time employment.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='notice_period',
            field=models.CharField(blank=True, help_text='e.g. "Available immediately", "2 weeks notice", "1 month".', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='open_to_employment',
            field=models.BooleanField(default=False, help_text='Shows an "Open to Work" badge and makes profile visible in talent search.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_match', 'New Job Match'), ('application_update', 'Application Status Update'), ('new_application', 'New Application Received'), ('new_review', 'New Review'), ('job_expiring', 'Job Expiring Soon'), ('profile_tip', 'Profile Improvement Tip'), ('system', 'System Message'), ('escrow_funded', 'Escrow Funded'), ('escrow_submitted', 'Work Submitted for Review'), ('escrow_approved', 'Milestone Approved'), ('escrow_released', 'Payment Released'), ('escrow_dispute', 'Dispute Raised'), ('hiring_interest_received', 'New Hire Interest Received'), ('hiring_interest_replied', 'Worker Replied to Outreach'), ('skill_endorsed', 'Your Skill Was Endorsed'), ('profile_saved', 'An Employer Saved Your Profile')], max_length=30),
        ),
    ]
