# Generated by Django 5.0.4 on 2026-06-16 06:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0005_add_escrow_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome class e.g. fas fa-tools",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Marketplace Category",
                "verbose_name_plural": "Marketplace Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offered_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price the buyer is offering in NGN.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "counter_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Counter-offer price from seller.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from buyer to seller."
                    ),
                ),
                (
                    "counter_message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from seller when countering.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("countered", "Countered"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Offer auto-expires after 48 hours if not responded to.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final agreed price in NGN (listed price or accepted offer).",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_fee_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Computed on completion: agreed_price × platform_fee_pct / 100",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "seller_payout_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="agreed_price - platform_fee_amount. Transferred to seller on completion.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "paystack_payment_ref",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transaction reference for the buyer payment.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "paystack_transfer_ref",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transfer reference for the seller payout.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid (In Escrow)"),
                            ("meetup_scheduled", "Meetup Scheduled"),
                            ("confirmed", "Buyer Confirmed Receipt"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "auto_complete_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-completes 7 days after buyer confirms receipt if no dispute.",
                        null=True,
                    ),
                ),
                (
                    "meetup_notes",
                    models.TextField(
                        blank=True, help_text="Location and time agreed for handover."
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set when order originated from an accepted offer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="marketplace.offer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_sales",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/disputes/"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("released_to_seller", "Released to Seller"),
                            ("refunded_to_buyer", "Refunded to Buyer"),
                            ("split", "Split"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute",
                        to="marketplace.order",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the item, its condition, age, brand, and any defects."
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("used_good", "Used — Good Condition"),
                            ("used_fair", "Used — Fair Condition"),
                            ("for_parts", "For Parts / Not Working"),
                        ],
                        default="used_good",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand or manufacturer e.g. Bosch, Dewalt",
                        max_length=100,
                    ),
                ),
                ("model_number", models.CharField(blank=True, max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Listed price in NGN. Buyers can make lower offers.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "min_offer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum offer the seller will consider (optional, not shown to buyers).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "offers_allowed",
                    models.BooleanField(
                        default=True, help_text="Allow buyers to make price offers."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("fct", "FCT — Abuja"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                        ],
                        max_length=40,
                    ),
                ),
                ("lga", models.CharField(blank=True, max_length=120)),
                (
                    "pickup_only",
                    models.BooleanField(
                        default=True,
                        help_text="Phase 1: all transactions are pickup/meetup.",
                    ),
                ),
                (
                    "pickup_notes",
                    models.TextField(
                        blank=True,
                        help_text="Meeting point, availability for pickup, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "slots",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Quantity available. Set to 1 for single items.",
                    ),
                ),
                (
                    "text_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Sentence-transformer embedding (768-dim) for semantic search.",
                        null=True,
                    ),
                ),
                ("text_embedding_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "platform_fee_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Platform fee percentage deducted from seller at payout.",
                        max_digits=5,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="marketplace.marketplacecategory",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Only verified WorkerProfiles can list products.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="jobs.workerprofile",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which trade this product is relevant to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_products",
                        to="jobs.tradecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="marketplace.product",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="marketplace.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="marketplace/products/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1–5 star rating.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="marketplace.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_reviews_received",
                        to="jobs.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="marketplace.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
