# Generated by Django 5.0.4 on 2026-06-20 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="market_median_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Median price of semantically similar products at time of last computation.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_percentile",
            field=models.FloatField(
                blank=True,
                help_text="Price percentile vs semantically similar products (0=cheapest, 100=most expensive).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="trending_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="Time-decayed popularity score, recomputed hourly. Higher = trending.",
            ),
        ),
        migrations.CreateModel(
            name="ProductRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("similar", "Similar Items"),
                            ("personal", "Personalised For User"),
                            ("trending", "Trending"),
                            ("cross_sell", "Cross-Sell"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Recommendation strength 0-1. Higher = stronger.",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "recommended",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_as_target",
                        to="marketplace.product",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_as_source",
                        to="marketplace.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["source_product", "rec_type", "-score"],
                        name="marketplace_source__93fe03_idx",
                    ),
                    models.Index(
                        fields=["user", "rec_type", "-score"],
                        name="marketplace_user_id_93023e_idx",
                    ),
                    models.Index(
                        fields=["rec_type", "-score"],
                        name="marketplace_rec_typ_0c7e93_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProductInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("save", "Saved / Bookmarked"),
                            ("offer", "Made Offer"),
                            ("purchase", "Purchased"),
                            ("chat", "Started Chat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="marketplace.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type", "-created_at"],
                        name="marketplace_user_id_497342_idx",
                    ),
                    models.Index(
                        fields=["product", "event_type"],
                        name="marketplace_product_3c301e_idx",
                    ),
                ],
            },
        ),
    ]
