# Generated by Django 5.0.4 on 2026-08-18 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_add_recommendation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdispute',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, help_text='Auto-release to seller 7 days after dispute creation if unresolved.', null=True),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='evidence_sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of evidence file at upload time (tamper detection).', max_length=64),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='mediation_buyer_agreed',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='mediation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='mediation_seller_agreed',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='split_seller_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For SPLIT resolution: percentage (0-100) released to the seller.', null=True),
        ),
        migrations.CreateModel(
            name='OrderDisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='marketplace/disputes/messages/')),
                ('attachment_sha256', models.CharField(blank=True, max_length=64)),
                ('is_admin_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.orderdispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
