# Generated by Django 5.0.4 on 2026-09-11 09:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0009_employerprofile_company_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_monthly_ngn', models.DecimalField(decimal_places=2, default=0, help_text='Monthly cost in NGN.  0 = free tier.', max_digits=10)),
                ('talent_searches_per_month', models.PositiveIntegerField(default=0, help_text='Max talent searches per month.  0 = unlimited.')),
                ('direct_outreach_per_month', models.PositiveIntegerField(default=0, help_text='Max direct outreach messages per month.  0 = unlimited.')),
                ('job_posts_per_month', models.PositiveIntegerField(default=0, help_text='Max full-time job posts per month.  0 = unlimited.')),
                ('can_download_cv', models.BooleanField(default=True, help_text='Whether employers on this plan can download worker CV PDFs.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ['price_monthly_ngn'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the certificate, e.g. NABTEB Electrical Installation Certificate.', max_length=200)),
                ('issuing_body', models.CharField(help_text='Organisation that issued the certificate, e.g. NABTEB, SON, City & Guilds, COREN.', max_length=200)),
                ('year_obtained', models.PositiveSmallIntegerField(blank=True, help_text='Year the certificate was awarded.', null=True, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('certificate_image', models.ImageField(blank=True, help_text='Upload a clear photo or scan of your certificate for verification.', null=True, upload_to='certifications/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admin after reviewing the uploaded certificate image.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-year_obtained', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = active until cancelled (free tier or lifetime).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_ref', models.CharField(blank=True, help_text='Paystack subscription code for recurring billing.', max_length=100)),
                ('searches_used', models.PositiveIntegerField(default=0)),
                ('outreach_used', models.PositiveIntegerField(default=0)),
                ('posts_used', models.PositiveIntegerField(default=0)),
                ('usage_reset_at', models.DateTimeField(blank=True, help_text='Timestamp of last monthly usage counter reset.', null=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='jobs.employerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='hiring.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Employer Subscription',
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_name', models.CharField(help_text='Name of the company, contractor, or client you worked for.', max_length=200)),
                ('role_title', models.CharField(help_text='Your job title, e.g. Lead Electrician, Site Foreman, Head Plumber.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What you did, what you built or fixed, tools & techniques used.')),
                ('start_date', models.DateField(help_text='When you started this role (YYYY-MM-DD).')),
                ('end_date', models.DateField(blank=True, help_text='When you left. Leave blank if this is your current role.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Tick if this is your current employer.')),
                ('location_state', models.CharField(blank=True, choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'FCT — Abuja'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], help_text='Which state the work was based in.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_category', models.ForeignKey(blank=True, help_text='Which trade discipline this role fell under.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.tradecategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Work History Entry',
                'verbose_name_plural': 'Work History',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HiringInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Introduction and interest message from the employer to the worker.')),
                ('salary_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Indicative monthly salary offer in NGN (optional — workers appreciate transparency).', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed by Worker'), ('interested', 'Worker Interested'), ('declined', 'Worker Declined'), ('hired', 'Hired')], default='sent', max_length=20)),
                ('worker_reply', models.TextField(blank=True, help_text="Worker's response message to the employer.")),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_sent', to='jobs.employerprofile')),
                ('job', models.ForeignKey(blank=True, help_text='Optional: link this outreach to a specific full-time job posting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_interests', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_received', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Hiring Interest',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['worker', 'status'], name='hiring_hiri_worker__a0c01f_idx'), models.Index(fields=['employer', 'status'], name='hiring_hiri_employe_3c9451_idx')],
                'unique_together': {('employer', 'worker', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SavedWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, help_text='Private employer note — only visible to you, not the worker.')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workers', to='jobs.employerprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_employers', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Saved Worker',
                'ordering': ['-saved_at'],
                'unique_together': {('employer', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='jobs.skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Skill Endorsement',
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'skill', 'endorsed_by')},
            },
        ),
    ]
